sudo: required
dist: trusty
group: stable

services:
  - docker

script:
  - docker build --pull --tag "strider2038/php-cli-dev" .
  - docker images

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch:
      - master
