sudo: required
dist: trusty
group: stable

services:
  - docker

script:
  - docker build --pull --tag "strider2038/php-cli-dev" .
  - docker build --build_arg PHP_VERSION=7.4 --pull --tag "strider2038/php-cli-dev:7.4" .
  - docker build --build_arg PHP_VERSION=7.3 --pull --tag "strider2038/php-cli-dev:7.3" .
  - docker build --build_arg PHP_VERSION=7.2 --pull --tag "strider2038/php-cli-dev:7.2" .
  - docker images

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch:
      - master
