name: Build docker

on:
  push:
    branches: [ '*' ]

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['8.0']
        file: ['Dockerfile']
        tag: [['strider2038/php-cli-dev:latest', 'strider2038/php-cli-dev:8.0']]
        include:
          - php_version: '7.4'
            file: 'Dockerfile.7.4'
            tag: 'strider2038/php-cli-dev:7.4'
          - php_version: '7.3'
            file: 'Dockerfile.7.3'
            tag: 'strider2038/php-cli-dev:7.3'

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          build_args: PHP_VERSION=${{ matrix.php_version }}
          file: ${{ matrix.file }}
          always_pull: true
          tags: strider2038/php-cli-dev:${{ matrix.tag }}
          tag_with_ref: true
